### ISSUE TITLE
Not working with DnD 4.0

### ISSUE THREAD

**Issue by LorduFreeman** [Skyl3lazer/foundry-5e-monster-maker-v10#71]
V12 3.31
DnD5e 4.0.3

Error Message: `Giffyglyph's 5e Monster Maker Continued: Error detected in module. It is likely this module has not been updated for FVTT Version 12 Stable. (See JS Console)`

And a few other errors as well like `foundry.js:655 Error: Failed data preparation for Scene.XVluodnmviJnoczl.Token.GC6kaSS8Q4eGSvLV.Actor.04S2RY8IakF6f81A.Item.kFPbmQZGCKfWRXpq. this.getSheetId is not a function`

**Comment by Skyl3lazer** [comment]
Yes, this is known. It will be a while before it is 4.0 compatible, there
are major changes in the system that would need to be accounted for.

**Comment by KirbyCrono** [comment]
Hi! This module is my salvation, but I was just wondering if this is still in development, since I'm interested in the D&D 4.x compatibility...
Hope so much for that! ;-)
Have a nice day! :-)

**Comment by Skyl3lazer** [comment]
Yeah I just haven't had the time and effort in me to do it. It's still on
my radar.

**Comment by yjeroen** [comment]
Would love to see this updated as well! <3

**Comment by Enthymeme** [comment]
+1 for me as well. You have fans.

**Comment by Skyl3lazer** [comment]
Fixed on branch v14dev
